### ISSUE TITLE
send_type can be empty string

### ISSUE THREAD

**Issue by Cruiser13** [j-mastr/sevdesk-php-sdk#47]
send_type (in orders, credit notes and so on) can be null according to the docs but it also can be an empty string ("").
This will throw an error by using the PHP SDK because it only allows send type VPR, VPDF, VM and VP:

>  Invalid value '' for 'send_type', must be one of 'VPR', 'VPDF', 'VM', 'VP'"

Query the order endpoint for orders to reproduce this.

**Comment by Cruiser13** [comment]
@j-mastr thank you for the quick fix. This solves our issue. We had the issue with the response. It seems that there is no documentation for this behaviour. We did not see any 0 values so far.

**Comment by j-mastr** [comment]
Great to hear that it fixed your issue!

Then maybe the `0` was something specific to our instance. Because of these deviations between the sevdesk docs and the actual behaviour, I started [j-mastr/sevdesk-api](https://github.com/j-mastr/sevdesk-api) in an attempt to create a community-sourced accurate version of the docs. Since the SDK is basically generated out of these docs, feel free to report such deviations or unsupported values/methods/... over there, either as an issue or PR :)
